spring:
  batch:
    jdbc:
      initialize-schema: always
    job:
      name: tickerJob

  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/tickit
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    root: INFO
    